/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TuningIndexRouteImport } from './routes/tuning/index'
import { Route as AlarmsIndexRouteImport } from './routes/alarms/index'
import { Route as SystemIndexRouteImport } from './routes/system/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningIndexRoute = TuningIndexRouteImport.update({
  id: '/tuning/',
  path: '/tuning/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsIndexRoute = AlarmsIndexRouteImport.update({
  id: '/alarms/',
  path: '/alarms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsIndexRoute
  '/tuning': typeof TuningIndexRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsIndexRoute
  '/tuning': typeof TuningIndexRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms/': typeof AlarmsIndexRoute
  '/tuning/': typeof TuningIndexRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alarms' | '/tuning' | '/system'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alarms' | '/tuning' | '/system'
  id: '__root__' | '/' | '/alarms/' | '/tuning/' | '/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsIndexRoute: typeof AlarmsIndexRoute
  TuningIndexRoute: typeof TuningIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning/': {
      id: '/tuning/'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof TuningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms/': {
      id: '/alarms/'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsIndexRoute: AlarmsIndexRoute,
  TuningIndexRoute: TuningIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
